### ISSUE TITLE
"TypeError: Cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by comafire** [maple3142/vuejs-storage#1]
Could you check this?, I've get below error, when I test your library in webpack based vuejs App. 

[Vue warn]: Error in callback for watcher "count": "TypeError: Cannot read property 'call' of undefined"

found in

---> <Test> at src/components/Test.vue
       <App> at src/App.vue
         <Root>

TypeError: Cannot read property 'call' of undefined
    at VueComponent.this_1.$options.watch.(anonymous function) (webpack-internal:///125:157:33)
    at Watcher.run (webpack-internal:///2:3201:19)
    at flushSchedulerQueue (webpack-internal:///2:2949:13)
    at Array.eval (webpack-internal:///2:1808:12)
    at MessagePort.flushCallbacks (webpack-internal:///2:1729:14)

[main.js]
import vuejsStorage from 'vuejs-storage'
Vue.use(vuejsStorage)

[Test.vue]
<template>
  <div class="layout-padding row justify-center">
    <div style="width: 700px; max-width: 90vw;">
      {{ count }}
      <q-btn color="secondary" @click="add">Add</q-btn>
    </div>
  </div>
</template>

<script>
import {
  QBtn
} from 'quasar'

export default {
  components: {
    QBtn
  },
  data () {
    var data = {}
    return data
  },
  storage: {
    data: {
      count: 0
    },
    storage: sessionStorage,
    namespace: 'my-namespace'
  },
  methods: {
    add () {
      this.count++
    }
  },
  computed: {
  }
}
</script>

**Comment by maple3142** [comment]
It is a bug, update to latest version and try again.
fixed in https://github.com/maple3142/vuejs-storage/blob/bfa9c3cfc7858018796ca3f5e4e5b8451699bcec/src/install.ts#L42

**Comment by comafire** [comment]
Thanks, quick response. your lib is very convenient.
I've tried, it's working well.
