### ISSUE TITLE
Loosing Vue reactivity with VueX plugin set

### ISSUE THREAD

**Issue by rderimay** [maple3142/vuejs-storage#12]
I have a pretty simple app where I want to persist a few preferences. 
I have set VueJS-Storage as vuex plugin. I see that the localStorage does correctly reflect the state but the computed data are not updated. 
Disabling vuejs-storage solves the problem and everything becomes reactive again.
It seems like an error would happen in the background without being reported (like in setTimeout).
I also tried to import ```vuejs-storage/dist/vuejs-storage.js``` but no error is output.

**Comment by maple3142** [comment]
Can you show me the code?

**Comment by maple3142** [comment]
Isn't `getPreference` a getter?
Why you call it in this line: `this.getPreference('RIGHTBAR_VISIBLE', this.visible)`.

**Comment by maple3142** [comment]
So what is your expected behavior and current expected behavior.
I create a [fiddle](https://jsfiddle.net/qjwdtv1m/2/) which use computed & getters, and everything works as expected.

**Comment by rderimay** [comment]
I could bet that the problem is coming from the line:
```store.replaceState(merge$$1(store.state, data)); //merge state```

I maybe totally wring because newbie in this matter, but plugins are not allowed to change state and have to do it though mutations.

Could it be the problem ?

**Comment by maple3142** [comment]
`replaceState` can be used in strict mode.
And [this](https://jsfiddle.net/zdp90fbs/) is a example which just copy your code to jsfiddle.
You can use `vm.$store.dispatch('setPreference',{key: 'RIGHTBAR_VISIBLE',value: false})` in console, and rightbar disappear as I expected.
If this is not your expected behavior, please tell me what you want.

**Comment by rderimay** [comment]
ok, thanks. I am pretty sure the simplified example showed previously will work, but the fact is that it does break all reactiveness of the attributes which I choose to be persisted when I add you plugin to by -bigger- project.
I tried to replace this module by `vuex-persist` and the exact same problem appeared.
That tend to prove that I must be doing something wrong or that the bug is in vuex itself which is not very likely...

**Comment by maple3142** [comment]
You could try `vuex-persistedstate`.
if it doesn't works either, I think it is Vuex or Vue bug.

**Comment by rderimay** [comment]
In fact, with `vuex-persistedstate`, this is working :-)

**Comment by maple3142** [comment]
Ok, I think you could switch to `vuex-persistedstate` for your project.
Because I cannot find any bug without others code.
