### ISSUE TITLE
vuejs-storage is not working

### ISSUE THREAD

**Issue by caihuattkl** [maple3142/vuejs-storage#26]
![image](https://user-images.githubusercontent.com/18523369/56076245-570da100-5e01-11e9-82bb-45c350ab34d5.png)

The value has been assigned to the store. But after the refresh, the data is lost! vuejs-storage is not working

**Comment by caihuattkl** [comment]
![image](https://user-images.githubusercontent.com/18523369/56076282-bcfa2880-5e01-11e9-91fd-dc0bfc655d5c.png)

**Comment by maple3142** [comment]
Could you show me your vuejs-storage configuration?

**Comment by caihuattkl** [comment]
![image](https://user-images.githubusercontent.com/18523369/56105698-25671800-5f70-11e9-83e9-d64038f78cea.png)

**Comment by caihuattkl** [comment]
this login is object.

**Comment by maple3142** [comment]
I think that you shouldn't modify modify computed from start, because this one rely on Vuex's internal callback system to work, which only work with mutations.
https://vuex.vuejs.org/guide/mutations.html

**Comment by maple3142** [comment]
This is how you should use Vuex & this plugin: https://codepen.io/anon/pen/axVoLJ
