### ISSUE TITLE
Type error when using in typescript

### ISSUE THREAD

**Issue by paparent** [maple3142/vuejs-storage#39]
In my `index.ts`, I have the following:

```ts
import vuejsStorage from 'vuejs-storage';

Vue.use(vuejsStorage);
```

But the `Vue.use` has the following error: `'vuejsStorage' only refers to a type, but is being used as a value here.ts(2693)`

I had this issue on `3.0.1` but after upgrading to the latest, I still have the error.

Another weird issue, might not be related. I don't know. When I run `npm run serve`, I get the following error! Can't find a way for typescript to not type check event if `node_modules` is in the excluded list

```
ERROR in _____/node_modules/vuejs-storage/src/drivers.ts(3,10):
3:10 Member 'storage' implicitly has an 'any' type.
    1 | import { StorageDriver } from './interfaces'
    2 | export default class StroageDriverImpl implements StorageDriver {
  > 3 |         private storage
      |                 ^
    4 |         constructor(storage: Storage) {
    5 |                 this.storage = storage
    6 |         }
```

**Comment by maple3142** [comment]
It works for me: https://codesandbox.io/s/cool-poitras-n704k
You can try disable implicit any check

**Comment by paparent** [comment]
@maple3142  Thanks for fast reply !! 

I just opened your snippet in VSCode and I still get the following error:

![image](https://user-images.githubusercontent.com/64377/91883041-da779e80-ec51-11ea-93e4-3d143c6e550e.png)

And regarding the 2nd point, to disable implicit any check, not sure I'd want to do that :(  There should be a better way! in my code, I want that setting :)  Maybe fixing the 1st issue will help?

See in the screenshot above, it doesn't recognize `storage` option too :( 

I'll try to help more maybe tonight! 

Thanks

**Comment by maple3142** [comment]
Can you provide a reproduction repo? With all the things I need to check this

**Comment by paparent** [comment]
@maple3142  I simply used your code. Downloaded the ZIP file from their UI, extract, `npm i`, and tried it.

**Comment by paparent** [comment]
@maple3142  ok, just created a sample repo: https://github.com/paparent/vuejs-storage-sample

Thanks!

**Comment by maple3142** [comment]
Fxied in 075f169dda327e4cdb55d8e84645dfbbc080a0f0
