### ISSUE TITLE
Support for vuex modules?

### ISSUE THREAD

**Issue by SchneiderPatrick** [maple3142/vuejs-storage#4]
Does this package support vuex modules?
If yes, how do I configure this?

Greets

**Comment by maple3142** [comment]
It is **not supported** currently by this package. But I think I can make some change to support it.
For example, make `keys` in vuex plugin option able to set module path.
```javascript
keys: ['conut','mymodule/count']
``` 
How do you think about that?

**Comment by SchneiderPatrick** [comment]
This is a good idea :+1:

**Comment by maple3142** [comment]
I find that I don't need to change anything.
Because this `keys` support some path like `a.b.c`, so nested object and module has already supported.

https://github.com/maple3142/vuejs-storage/blob/5f8b04af0ae173bac2cf14ef3e4634645027010e/test/vuexplugin.ts#L103-L123

**Comment by maple3142** [comment]
@SchneiderPatrick Does it works?
If solved, I will close this issue.

**Comment by SchneiderPatrick** [comment]
@maple3142 This solved my problem. Thanks a lot! :)

You should update your docs ;)

**Comment by maple3142** [comment]
Docs update in a8a68537ac67dcfb4b8ce98b28813b61459b2805
