### ISSUE TITLE
Vuex modules strange behaviour - Typescript

### ISSUE THREAD

**Issue by AndreaMinato** [maple3142/vuejs-storage#9]
### the problem
Hi i am having some problem with your plugin since i separated my vuex store into modules.
it does not take the state within the getters.

### the code
[here](https://gist.github.com/AndreaMinato/acf06c8d3f8186e0681119d4b540eb02) you can find a gist with my code

### consideration
it is fairly possible that i have done some kind of errors since is the first time i work with typescript, but everything work as expected if i comment the plugin array within store.ts

**Comment by maple3142** [comment]
Could you show what doesn't working?
In [this fiddle](https://jsfiddle.net/maple3142/drgzj1h3/), vuex modules state is persisted as my expectation.

**Comment by AndreaMinato** [comment]
The state is persisted but in the components and in the getters returns undefined.
it has begun since i separated into modules, than since i couldn't find the error i started to simplify the store.
Now It works as expected if i comment the plugin

**Comment by AndreaMinato** [comment]
In addiction, some of the state values work as expected (username for example), loginError instead does not work

**Comment by maple3142** [comment]
Try updating to version `2.3.3`, it should work now.

**Comment by AndreaMinato** [comment]
Still doesn't work in my case

**Comment by maple3142** [comment]
I finally realized that how did that happen...
It is because internal merge function is a **shallow clone** function like `Objec.assign`.
It should be solved if you pass a **deep clone** function to `merge` option, like `_.cloneDeep`.

But there is room for discussion about should this module include **deep clone** function inside or not.
I implement those thing instead of importing npm modules is order to reduce the bundle size.

[This](https://github.com/maple3142/vuejs-storage/blob/master/src/assign.ts) is how internal merge function works.

**Comment by maple3142** [comment]
Example: https://jsfiddle.net/maple3142/drgzj1h3/

**Comment by AndreaMinato** [comment]
#### store.ts
```typescript
import Vue from "vue";
import Vuex from "vuex";

import storage from "vuejs-storage";

import auth from "./modules/auth";
import navigation from "./modules/navigation";

Vue.use(Vuex);

export default new Vuex.Store({
  modules: {
    auth,
    navigation
  },
  state: {
    isAppLoading: false
  },
  mutations: {
    changeAppLoadingState(state: any, appLoadingState) {
      state.isAppLoading = appLoadingState;
    }
  },

  actions: {},

  plugins: [
    storage({
      namespace: "test_session",
      storage: window.sessionStorage,
      keys: [
        "auth.loggedIn",
        "navigation.breadcrumb",
        "navigation.currentPosition"
      ],
      merge: _.cloneDeep
    }),
    storage({
      namespace: "test_local",
      keys: ["auth.username"],
      merge: _.cloneDeep
    })
  ]
});
```

It says that it cannot find name _.
I believe it is due to typescript, any thoughts?

**Comment by maple3142** [comment]
Symbol `_` usually means [lodash](https://lodash.com/) (a popular js library).
So you need to `import _ from 'lodash'`, and `npm i lodash -S`.

**Comment by maple3142** [comment]
Besides, if you want a simple merging function instead a big library.
You can use this(not fully tested)
```js
const isobj=x=>typeof x==='object'&&!Array.isArray(x)&&x!==null
const merge=(obj1,...objs)=>{
	console.log('a',JSON.stringify(obj1),JSON.stringify(objs[0]))
	for(const obj2 of objs){
  	for(const k in obj2){
    	if(!obj2.hasOwnProperty(k))continue
      if(isobj(obj1[k])&&isobj(obj2[k]))merge(obj1[k],obj2[k])
      else obj1[k]=obj2[k]
    }
  }
  return obj1
}
```

**Comment by AndreaMinato** [comment]
I know and i had imported it, i was missing
`
npm install @types/lodash --save-dev
`
for typescript.

It seems to work with loadash i could try this script if you want and report if it does the job

**Comment by maple3142** [comment]
@AndreaMinato You can use `v2.4.0` now, which include deep merging function inside.

**Comment by AndreaMinato** [comment]
Updated to version `2.4.0`, removed lodash, cleared storage, session and all other site data.

It all works until i have an object inside my vuex state


#### Error Log
```
vuejs-storage.min.js?6da9:1 Uncaught TypeError: Cannot set property 'id' of null
    at o (vuejs-storage.min.js?6da9:1)
    at o (vuejs-storage.min.js?6da9:1)
    at o (vuejs-storage.min.js?6da9:1)
    at eval (vuejs-storage.min.js?6da9:1)
    at eval (vuex.esm.js?358c:351)
    at Array.forEach (<anonymous>)
    at new Store (vuex.esm.js?358c:351)
    at eval (store.ts?57f0:13)
    at Object../src/store/store.ts (app.js:1464)
    at __webpack_require__ (app.js:679)
```
#### Session storage (same for local but it has only a string so it works)
![image](https://user-images.githubusercontent.com/15440218/39986658-a34863c6-5762-11e8-9eaa-a6320f63141b.png)

#### store.ts
```javascript
import Vue from "vue";
import Vuex from "vuex";

import storage from "vuejs-storage";

import auth from "./modules/auth";
import navigation from "./modules/navigation";

Vue.use(Vuex);

export default new Vuex.Store({
  modules: {
    auth,
    navigation
  },
  state: {
    isAppLoading: false
  },
  mutations: {
    changeAppLoadingState(state: any, appLoadingState) {
      state.isAppLoading = appLoadingState;
    }
  },

  actions: {},

  plugins: [
    storage({
      namespace: "test_session",
      storage: window.sessionStorage,
      keys: [
        "auth.loggedIn",
        "navigation.breadcrumb",
        "navigation.currentPosition"
      ],
    }),
    storage({
      namespace: "test_local",
      keys: ["auth.username"],
    })
  ]
});

```

**Comment by AndreaMinato** [comment]
```
vuejs-storage.js?3783:68 Uncaught TypeError: Cannot set property 'id' of null
    at merge (vuejs-storage.js?3783:68)
    at merge (vuejs-storage.js?3783:66)
    at merge (vuejs-storage.js?3783:66)
    at eval (vuejs-storage.js?3783:146)
    at eval (vuex.esm.js?358c:351)
    at Array.forEach (<anonymous>)
    at new Store (vuex.esm.js?358c:351)
    at eval (store.ts?57f0:13)
    at Object../src/store/store.ts (app.js:1464)
    at __webpack_require__ (app.js:679)


merge | @ | vuejs-storage.js?3783:68
-- | -- | --
  | merge | @ | vuejs-storage.js?3783:66
  | merge | @ | vuejs-storage.js?3783:66
  | (anonymous) | @ | vuejs-storage.js?3783:146
  | (anonymous) | @ | vuex.esm.js?358c:351
  | Store | @ | vuex.esm.js?358c:351
  | (anonymous) | @ | store.ts?57f0:13
  | ./src/store/store.ts | @ | app.js:1464
  | __webpack_require__ | @ | app.js:679
  | fn | @ | app.js:89
  | (anonymous) | @ | router.ts?dbe3:1
  | ./src/router.ts | @ | app.js:1440
  | __webpack_require__ | @ | app.js:679
  | fn | @ | app.js:89
  | (anonymous) | @ | main.ts?c77e:1
  | ./src/main.ts | @ | app.js:1424
  | __webpack_require__ | @ | app.js:679
  | fn | @ | app.js:89
  | 0 | @ | app.js:1503
  | __webpack_require__ | @ | app.js:679
  | (anonymous) | @ | app.js:725
  | (anonymous) | @ | app.js:728

```

**Comment by maple3142** [comment]
I think it is a issue about `merge`, but I cannot reproduce it.
I added some test in https://github.com/maple3142/vuejs-storage/commit/8ea21f69b65dc3abffa651b0d337e0c62914077f, but all tests still passed, did I miss anything?

**Comment by AndreaMinato** [comment]
I don't know maybe something like this should be more similar to my case:

```js
// your code
  modules: {
    test: {
      state: {
        ar: [{ value: 1 }, { value: 2 }],
        wontBeSave: 1,
        customObject: {
          propA: "some sort of string here",
          propB: "another string here"
        }
      }
    }
  }
//your code
```

**Comment by AndreaMinato** [comment]
@maple3142 So i have cloned your repo to dive deeper into the code and I saw that the test check if the selected storage is saved in the right way.

The storage is correct but in some way i believe it fails when vuex read from it.

So i put a breakpoint in the merge function and i found what was wrong.

#### navigationModule.ts
```ts
const navigationModule: Module<any, any> = {
  state: {
    currentPosition: null, //Here i must use {}
    breadcrumb: []
  },
  getters: {},
  mutations: {  },
  actions: {}
};
```
in the merge after some iteration vuejs-storage try to put into my state.navigation.currentPosition[prop] what is stored in the session under storage.navigation.currentPosition[prop], but currentPosition in the state is null due to my declaration. so I changed de default value of the object to {} instead of null.

now it seems to work

**Comment by maple3142** [comment]
I think this problem is solved now, but I will add this issue to docs to prevent someone from encountering same problem.

**Comment by ngekoding** [comment]
I got the same problem because using null for the value, change to {} make it works. But I think the null value is better, any idea?
